import os
import streamlit as st
from google import genai
from utils import BASELINE_YEAR, LATEST_YEAR


def render_ai_analyst(df, trend_df):
    st.header("AI Risk Analyst — ZIP Code Lending Brief")
    st.caption(
        "Select a ZIP code to generate an AI-powered lending risk memo. "
        "The analyst synthesizes AGI growth, income quality, and trend data "
        "into a concise recommendation."
    )

    valid = df.dropna(subset=["agi_cagr", "iqri", "iqri_tier"]).copy()

    col1, col2 = st.columns(2)
    with col1:
        state = st.selectbox("State", sorted(valid["STATE"].unique()))
    with col2:
        zips = valid[valid["STATE"] == state]["zipcode"].sort_values().tolist()
        zipcode = st.selectbox("ZIP Code", zips)

    row = valid[(valid["STATE"] == state) & (valid["zipcode"] == zipcode)]
    if row.empty:
        st.warning("No data for this ZIP.")
        return
    row = row.iloc[0]

    m1, m2, m3, m4 = st.columns(4)
    m1.metric("AGI CAGR", f"{row['agi_cagr']:.2f}%")
    m2.metric("Status", row["status"])
    m3.metric("IQRI Score", f"{row['iqri']:.3f}")
    m4.metric("Income Tier", str(row["iqri_tier"]))

    if st.button("Generate Risk Memo", type="primary"):
        zip_trend = trend_df[trend_df["zipcode"] == zipcode].sort_values("year")
        trend_lines = "\n".join(
            f"  {int(r['year'])}: AGI=${r['agi']:,.0f}K, Returns={int(r['returns']):,}"
            for _, r in zip_trend.iterrows()
        )

        prompt = f"""You are a senior risk analyst at an investment bank reviewing ZIP code data.
Write a 200-300 word lending risk assessment memo for ZIP code {zipcode} ({state}).

Data:
- AGI CAGR ({BASELINE_YEAR}–{LATEST_YEAR}): {row['agi_cagr']:.2f}%
- Economic Status: {row['status']}
- Total AGI {LATEST_YEAR}: ${row[f'A00100_{LATEST_YEAR}']:,.0f}K
- Total AGI {BASELINE_YEAR}: ${row[f'A00100_{BASELINE_YEAR}']:,.0f}K
- Total Growth: {row['agi_total_growth_pct']:.1f}%
- IQRI Score: {row['iqri']:.3f} ({row['iqri_tier']})
- Tax Returns Filed ({LATEST_YEAR}): {int(row[f'N1_{LATEST_YEAR}']):,}

Year-over-year trend:
{trend_lines}

Structure the memo as:
1. Executive Summary (2 sentences)
2. Key Risk Factors
3. Key Opportunities
4. Lending Recommendation (Approve / Caution / Avoid)

Be concise and professional. Ground every claim in the data provided."""

        try:
            api_key = st.secrets.get("GOOGLE_API_KEY", "") or os.environ.get("GOOGLE_API_KEY", "")
        except Exception:
            api_key = os.environ.get("GOOGLE_API_KEY", "")
        if not api_key:
            st.error("GOOGLE_API_KEY not configured. Set it in Streamlit secrets or as an environment variable.")
            return

        with st.spinner("Analyzing ZIP code..."):
            client = genai.Client(api_key=api_key)
            response = client.models.generate_content(
                model="gemini-2.0-flash",
                contents=prompt,
            )
        st.markdown("---")
        st.markdown("### Lending Risk Memo")
        st.markdown(response.text)
        st.caption(f"Generated by Gemini · ZIP {zipcode} ({state}) · IRS SOI {BASELINE_YEAR}–{LATEST_YEAR}")
